# Generated by Django 3.1.2 on 2020-12-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
