# Generated by Django 3.1.2 on 2021-02-19 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0003_auto_20201220_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(max_length=2083)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('area', models.DecimalField(decimal_places=4, max_digits=8)),
                ('location', models.TextField()),
                ('posted_author', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('posted_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('item_code', models.CharField(max_length=255)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2083, null=True), null=True, size=None)),
                ('facade', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('entrance', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('orientation', models.CharField(max_length=255, null=True)),
                ('furniture', models.TextField(null=True)),
                ('policy', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
